//Selected
export const DELETE_SELECTED_FILLING = 'DELETE_SELECTED_FILLING';
export const UPDATE_SELECTED_FILLINGS = 'UPDATE_SELECTED_FILLINGS';
export const UPDATE_SELECTED_BUNS = 'UPDATE_SELECTED_BUNS';
export const ADD_SELECTED_FILLING = 'ADD_SELECTED_FILLING';
export const DELETE_SELECTED_LIST = 'DELETE_SELECTED_LIST';

//Details Ingredient
export const UPDATE_DETAILS_INGREDIENT = 'UPDATE_DETAILS_INGREDIENT';
export const DELETE_DETAILS_INGREDIENT = 'DELETE_DETAILS_INGREDIENT';

//ingredients
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';

//Order
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const DELETE_ORDER = 'DELETE_ORDER';

//Запрос данных о пользователе
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

//Обновление данных о пользователе
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

//Запрос на регистрацию пользователя
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

//Запрос на вход по логину
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

//Запрос на выход пользователя
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

//Запрос кода, если забыл пароль
export const CODE_USER_FAILED = 'CODE_USER_FAILED';
export const CODE_USER_REQUEST = 'CODE_USER_REQUEST';
export const CODE_USER_SUCCESS = 'CODE_USER_SUCCESS';

//Запрос на смену пароля
export const PASSWORD_CHANGE_USER_FAILED = 'PASSWORD_CHANGE_USER_FAILED';
export const PASSWORD_CHANGE_USER_REQUEST = 'PASSWORD_CHANGE_USER_REQUEST';
export const PASSWORD_CHANGE_USER_SUCCESS = 'PASSWORD_CHANGE_USER_SUCCESS';
